definitions:
  common.AppError:
    properties:
      error:
        type: string
      log:
        type: string
      message:
        type: string
    type: object
  common.Pagination:
    properties:
      page:
        minimum: 1
        type: integer
      pageSize:
        maximum: 1000
        minimum: 0
        type: integer
      total:
        type: integer
    type: object
  common.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      metadata:
        $ref: '#/definitions/common.Pagination'
    type: object
info:
  contact: {}
paths:
  /auth/profile:
    get:
      consumes:
      - application/json
      description: get user profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.AppError'
      security:
      - ApiKeyAuth: []
      summary: Show an account
      tags:
      - auth
swagger: "2.0"
